<?php

namespace Fourthwall\Enums;

enum WebhookType: string {

    case ORDER_PLACED = 'ORDER_PLACED';

    case ORDER_UPDATED = 'ORDER_UPDATED';

    case GIFT_PURCHASE = 'GIFT_PURCHASE';

    case DONATION = 'DONATION';

    case PRODUCT_CREATED = 'PRODUCT_CREATED';

    case PRODUCT_UPDATED = 'PRODUCT_UPDATED';

    case SUBSCRIPTION_PURCHASED = 'SUBSCRIPTION_PURCHASED';

    case SUBSCRIPTION_CHANGED = 'SUBSCRIPTION_CHANGED';

    case SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION_EXPIRED';

    case THANK_YOU_SENT = 'THANK_YOU_SENT';

    case NEWSLETTER_SUBSCRIBED = 'NEWSLETTER_SUBSCRIBED';
}